; Generated: only animated title cells change during vblank.
 lda _art_bank
 clc
 adc #0
 sta $5cc3
 lda _art_bank
 clc
 adc #0
 sta $5cdc
 lda _art_bank
 clc
 adc #0
 sta $5d63
 lda _art_bank
 clc
 adc #0
 sta $5d7c
 lda _art_bank
 clc
 adc #64
 sta $5e2e
 lda _art_bank
 clc
 adc #64
 sta $5e2f
 lda _art_bank
 clc
 adc #64
 sta $5e30
 lda _art_bank
 clc
 adc #64
 sta $5e31
 lda _art_bank
 clc
 adc #64
 sta $5e46
 lda _art_bank
 clc
 adc #64
 sta $5e47
 lda _art_bank
 clc
 adc #64
 sta $5e48
 lda _art_bank
 clc
 adc #64
 sta $5e49
 lda _art_bank
 clc
 adc #64
 sta $5e4e
 lda _art_bank
 clc
 adc #64
 sta $5e4f
 lda _art_bank
 clc
 adc #64
 sta $5e50
 lda _art_bank
 clc
 adc #64
 sta $5e51
 lda _art_bank
 clc
 adc #64
 sta $5e56
 lda _art_bank
 clc
 adc #64
 sta $5e57
 lda _art_bank
 clc
 adc #64
 sta $5e58
 lda _art_bank
 clc
 adc #64
 sta $5e59
