"""Compile the reviewable reference-song score; no audio libraries are needed."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SEMITONES = {'C': 0, 'Cs': 1, 'D': 2, 'Ds': 3, 'E': 4, 'F': 5,
             'Fs': 6, 'G': 7, 'Gs': 8, 'A': 9, 'As': 10, 'B': 11}


def midi(note):
    match = re.fullmatch(r'([A-G]s?)([0-8])', note)
    if not match:
        raise ValueError(f'Invalid note: {note}')
    return 12 * (int(match[2]) + 1) + SEMITONES[match[1]]


def compile_scores():
    scores = json.loads((ROOT / 'assets/song-arrangements.json').read_text(encoding='utf-8'))['scores']
    assert [s['id'] for s in scores] == ['menu', 'estefania']
    leads, basses, drums, volumes = [], [], [], []
    for score in scores:
        lead = []
        for note, duration in score['lead_sixteenths']:
            assert isinstance(duration, int) and duration > 0
            pitch = 0 if note == 'R' else midi(note) - 35
            assert 0 <= pitch <= 49
            lead.append(pitch)
            lead.extend([pitch | 128 if pitch else 0] * (duration - 1))
        assert len(lead) == 64, (score['id'], len(lead))
        # Triangle oscillates one octave below the pulse timer's pitch.
        bass = [midi(n) + 12 - 35 for n in score['bass_quarters']]
        assert len(bass) == 16 and all(1 <= n <= 49 for n in bass)
        assert len(score['noise_periods']) == len(score['noise_volumes']) == 16
        assert all(0 <= n <= 15 for n in score['noise_periods'] + score['noise_volumes'])
        leads.append(lead); basses.append(bass)
        drums.append(score['noise_periods']); volumes.append(score['noise_volumes'])
    periods = [0] + [round(1789773 / (16 * 440 * 2 ** ((n - 69) / 12)) - 1) for n in range(36, 85)]
    assert all(8 <= p <= 2047 for p in periods[1:])
    lines = ['/* Generated by tools/generate_music.py from assets/song-arrangements.json. */',
             '#pragma rodata-name(push, "BOOTDATA")',
             'const u16 reference_periods[50]={' + ','.join(map(str, periods)) + '};']
    for name, values in [('leads', leads), ('basses', basses), ('drums', drums), ('volumes', volumes)]:
        lines += [f'const u8 reference_{name}[2][{len(values[0])}]={{']
        lines += [' {' + ','.join(map(str, row)) + '}' + (',' if i == 0 else '') for i, row in enumerate(values)]
        lines += ['};']
    lines += ['#pragma rodata-name(pop)', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    (ROOT / 'src/music_reference_data.h').write_text(compile_scores(), encoding='utf-8', newline='\n')
    print('Built reference-song score: two four-bar loops')
